spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gestao_financeira}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e9d3425c7ec2fce3b90b28a5}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
